config/routes.rb
BenjamRails::Application.routes.draw do

  root 'items#index'

  get 'cache.manifest' => 'cache#index'

resources :clients do
   get 'chooser' => 'chooser#index'
   resources :items do
      get 'index'
      get 'nested' => 'items#new'
   member do
        get 'image'
        get 'audio'
    end
  end
end

resources :items do
   member do
        get 'image'
        get 'audio'
    end
  end

end

app/models/client.rb
class Client < ActiveRecord::Base

    has_many :items
    
end

app/models/event.rb
class Event < ActiveRecord::Base
  
  belongs_to :client
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :children, class_name: "Item",
                          foreign_key: "parent_id"
 
  belongs_to :parent, class_name: "Item"

  belongs_to :client

  ROOT='I want...'

  def self.root
    Item.where("name = ?",ROOT).first 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

end

app/controllers/blahs_controller.rb
class BlahsController < ApplicationController
  # GET /blahs
  # GET /blahs.json
  def index
  end
end

app/controllers/cache_controller.rb
class CacheController < ApplicationController
  def index
  	@mode = cookies[:mode]
  	@items = Item.all
    @environment = Rails.application.assets
    @asset_list = @environment.each_logical_path(*Rails.application.config.assets).to_a

  	render layout: false
  	response.headers['Content-Type'] = 'text/cache-manifest'
  end
end

app/controllers/chooser_controller.rb
class ChooserController < ApplicationController
  def index
    @client = Client.where('name = ?', params[:client_id]).first
  	
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

 def show 
    @mode = params[:mode] || cookies[:mode] || 'default'
     
    @client = Client.where('name = ?', params[:id]).first
    @items = Item.order(:position).where('client_id = ? and parent_id IS NULL',@client.id)
    respond_to do |format|
        format.html {
             @item = Item.new
             @item.name = "#{@client.name} homepage"
             @item.client = @client
             render :template => "items/index" 
        }
        format.json {
            extract = []
            @items.each do |i|
                extract << item_extract(i)
            end
            render :json => extract
            
        }
    end
  end  

    def item_extract(item)
     return { :id => item.id, :name => item.name, :position => item.position, :parent_id => item.parent_id,
         :image => item_path(item.id) + "/image.jpg", :audio => item_path(item.id) + "/audio.mpeg" }
      end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController


before_filter :set_client

  # GET /events
  # GET /events.json
  def index
    @events = Event.where("client_id = ?",@client.id)
  end

  def create
    eventToCreate = Event.new()
    eventToCreate.event_type = params[:name]
    eventToCreate.description = params[:description]
    eventToCreate.client = @client
    eventToCreate.save

    respond_to do |format|
      format.html { redirect_to client_events_path(@client), notice: 'Created'}
      format.json { render json:  eventToCreate}
    end

  end

  def set_client
    @client = Client.where('name = ?', params[:client_id]).first if params[:client_id]
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def show
    render json: [:apple, :banana, :pool, :water, :computer, :toast, :tv, :hi5, :marshmallow]
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

respond_to :html, :json
before_filter :set_client ,except: [:audio, :image]

# GET /items
# GET /items.json
# GET /items/1/items
# GET /items/1/items.json
  def index

    @mode = params[:mode] || cookies[:mode] || 'default'
    @client = Client.where('name = ?', params[:client_id]).first
    @item = params[:item_id] == nil ? Item.root : Item.find(params[:item_id])
    @items = Item.order(:position).where('parent_id = ? AND client_id = ?', @item.id, @client.id)

    respond_to do |format|
        format.html {
            respond_with @items
        }
        format.json {
            extract = []
            @items.each do |i|
                extract << item_extract(i)
            end
            render :json => extract
            
        }
    end
  end

  def chooser

  end

# GET /items/1/images.jpg
 def image
     @item = Item.find(params[:id])
     respond_to do |format|
         format.jpg do
             self.response.headers["Content-Type"] ||= 'image/jpg'
             send_data @item.image, options = { :type => 'image/jpg', :disposition => 'inline'}
            end
     end
 end
 # GET /items/1/audio.mpeg
def audio
    @item = Item.find(params[:id])
    respond_to do |format|
        format.mpeg do
            self.response.headers["Content-Type"] ||= 'audio/mpeg'
            send_data @item.audio,  options: {type:'audio/mpeg; header=present', disposition:'inline'}
        end        
    end
end

# GET /items/1
# GET /items/1.json
 def show
    @mode =  params[:mode] || cookies[:mode] || 'default'

    @item = Item.find(params[:id])
    @items = @item.children.order(:position)
    respond_to do |format|
        format.html {
            if(@items.empty?)
                render :show_choice
            else
                render :show
            end
        }
        format.json {
            render :json => item_extract(@item)
        }
    end
  end  


  def new
    @item = Item.new new_item_params
    if params[:item_id]
      @item.parent_id = params[:item_id]
      @item.position = Item.where(parent_id: params[:item_id]).count + 1
    end
  end

  def create
    @item = Item.new item_params
    @item.image = params[:item][:image].read if params[:item][:image]
    @item.audio = params[:item][:audio].read if params[:item][:audio]
    @item.client = @client
    puts @item.inspect
    @item.save
    if params[:item][:parent_id].present?
      path = client_item_path(@client.name, @item.parent)
    else
      path = client_path(@client.name)
    end
    respond_to do |format|
      format.html { redirect_to path, notice: 'Created'}
      format.json { render json: @item }
    end

  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    if @item.parent
      path = client_item_path(@client.name, @item.parent)
    else
      path = client_path(@client.name)
    end

    respond_to do |format|
      format.html { redirect_to path, notice: 'Item deleted' }
      format.json { head :no_content , status: :ok}
    end
  end

  def set_client
    @client = Client.where('name = ?', params[:client_id]).first if params[:client_id]
    @client = Client.where('name = ?', params[:item][:client_id]).first if params[:item] && params[:item][:client_id]
  end

  private

  def new_item_params
    params.permit(:name, :parent_id, :position, :image, :audio,:client_id)
  end

  def item_params
    params.require(:item).permit(:name, :parent_id, :position)
  end
  
  def item_extract(item)
      return { :id => item.id, :name => item.name, :position => item.position, :parent_id => item.parent_id,
          :image => item_path(item.id) + "/image.jpg", :audio => item_path(item.id) + "/audio.mpeg" }
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def paths_for_manifests(manifests = [])
    manifests.map do |manifest|
      Rails.application.assets[manifest].dependencies.map{|d| "#{d.logical_path}"}
    end.flatten
  end

  def build_digested_asset_path(asset, add_body = false)
    environment = Rails.application.assets
    if
      (!Rails.env.production? && (asset == 'application.js' || asset == 'application.css')) ||
      (!Rails.env.production? && add_body)
      "/assets/#{environment.find_asset(asset).digest_path}?body=1" rescue nil
    else
      "/assets/#{environment.find_asset(asset).digest_path}" rescue nil
    end
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/cache/index.html.erb
CACHE MANIFEST

# <%= @mode %>
/jquery.flexslider.js
/arrows.png

<% unless Rails.env.production? %>
<% paths_for_manifests(%w(application.js)).each do |manifest_path| %>
<%= build_digested_asset_path manifest_path, true %>
<% end %>
<% end %>

<% @asset_list.each do |asset| %>
<%= build_digested_asset_path asset %>
<% end %>

<% @items.each do |item| %>
<%= client_item_path item.client.name, item %>
<%= image_item_path(item, format: :jpg) %>
<%= audio_item_path(item, format: :mpeg) %>
<% end %>

app/views/chooser/index.html.erb
<section class="chosen-item-callout">

  <h1 class="chosen-item-callout__heading">Choose the scrolling mode</h1>

  <script type="text/javascript">
  $(function() {
    $(".choose_button").click(function(ev) {
      console.log(ev);
      document.cookie = "mode=" + $(ev.target).data('cid');
      window.location = '<%= client_path(@client.name) %>';
    });
  });
  </script>
  
  <form>
    <button type="button" class="choose_button" data-cid="default">Original</button>
    <button type="button" class="choose_button" data-cid="slide">Swipe</button>
	<button type="button" class="choose_button" data-cid="carousel">Carousel</button>
  </form>

</section>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <thead>
    <tr>
      <th>Event type</th>
      <th>Description</th>
      <th>Create date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.event_type %></td>
        <td><%= event.description %></td>
        <td><%= event.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/items/_group_page.html.erb
<section class="group-cards" id="group-cards-container">
  <div id="item-heading"><%=current_item.name%></div>

  <div id="all_cards">
  <% @items.each do | item |%>
    <a class="group-card" href="<%= client_item_path(item.client.name,item.id) %>" >
  		<img class="group-card__image" src="<%= image_item_path(item, format: :jpg) %>">
      <h2 class="group-card__header"><%= item.name%></h2>
       <%if current_item.audio %>
      	<audio  src="<%= audio_item_path(item, format: :wav) %>" autobuffer="true"></audio>
	   <%end%>

    </a>
      <% end %>
  </div>
</section>

<script type="text/javascript">

$(document).ready(function(){
    $.post("<%=client_events_path(@client.name)%>",
    {
        name: "Selected Category",
        description: '<%= "client has drilled into #{current_item.name}"%>'
    },
    function(data, status){
    });
});
</script>

app/views/items/_group_page_carousel.html.erb
<script type="text/javascript">
$(function() {
$('ul li:even').addClass('even');
$('ul li:odd').addClass('odd');
setTimeout(RotateCarousel(), 3000);
function RotateCarousel() {  
    $("ul li:first-child").animate({ marginLeft: -700  }, 2500, 'linear', function () {
        $("ul li:first-child").appendTo('ul');
        $("ul li:last-child").css('margin-Left', 10);
        RotateCarousel();
    });
}
});
</script>

<section class="group-cards" id="group-cards-container">
  <div id="item-heading"><%=current_item.name%></div>
  <div id="all_cards">  		
			<div id="carousel_list">
			  <ul>
					 <% @items.each do | item |%>
        <%if current_item.audio %>
        <audio  src="<%= audio_item_path(item, format: :mpeg) %>" autobuffer="true"></audio>
     <%end%>
						<li><a href="<%= client_item_path(item.client.name,item.id) %>" >
						<img  src="<%= image_item_path(item, format: :jpg) %>" width="60%" height="60%">
						  <h2 class="group-card__header"><%= item.name%></h2>
						  </a></li>
						  <% end %>
               </ul>			
		</div>
  </div>
</section>

app/views/items/_group_page_default.html.erb
<section class="group-cards" id="group-cards-container">
  <div id="item-heading"><%=current_item.name%></div>

  <div id="all_cards">
  <% @items.each do | item |%>
    <a class="group-card" href="<%= client_item_path(item.client.name,item.id) %>" >
  		<img class="group-card__image" src="<%= image_item_path(item, format: :jpg) %>">
      <h2 class="group-card__header"><%= item.name%></h2>
       <%if current_item.audio %>
      	<audio  src="<%= audio_item_path(item, format: :mpeg) %>" autobuffer="true"></audio>
	   <%end%>

    </a>
      <% end %>
  </div>
</section>

app/views/items/_group_page_slide.html.erb
<style>
.flex-control-paging { display: none; }
.flex-nav-prev { position: absolute; left: 50px; top: -160px; }
.flex-nav-next { position: absolute; right: 50px; top: -160px; }
.flex-next { font-size: 0px; background: url(/arrows.png); background-position: 100% 0%; display: inline-block; width: 54px; height: 54px; }
.flex-prev { font-size: 0px; background: url(/arrows.png); display: inline-block; width: 54px; height: 54px; }
.flexslider ul, li { list-style-type: none; }
.flexslider {  position: absolute; top: 200px; left: 200px; right: 30px; }
.slides img { margin-right: auto; margin-bottom: auto; }
</style>

<script src="/jquery.flexslider.js"></script>


<script type="text/javascript" charset="utf-8">
  $(window).load(function() {
    $('.flexslider').flexslider({
    	animation: 'slide',
    	slideshow: false,
    });
  });
</script>

<section class="group-cards" id="group-cards-container">
  <div id="item-heading"><%=current_item.name%></div>
	<div class="flexslider">
	  <ul class="slides">
	  <% @items.each do | item |%>
        <%if current_item.audio %>
      	<audio  src="<%= audio_item_path(item, format: :mpeg) %>" autobuffer="true"></audio>
	   <%end%>
	    <li>
	      <div>
	    	<a class="group-card" href="<%= client_item_path(item.client.name,item.id) %>" >
		  	  <img src="<%= image_item_path(item, format: :jpg) %>">
		      <h2 class="group-card__header"><%= item.name%></h2>
		    </a>
	      </div>
	    </li>

	  <% end %>
	  </ul>
	</div>



</section>

app/views/items/index.html.erb
<%= render "items/group_page_#{@mode}",
                   items: @items, current_item: @item%> 

app/views/items/new.html.erb
<section class="chosen-item-callout">

  <h1 class="chosen-item-callout__heading">New Item</h1>
  <%= form_for @item, html: {multipart: true, role: "form"} do |f| %>
    <%= f.hidden_field 'parent_id', parent_id: @item.parent_id%>
    <%= f.hidden_field 'client_id', client_id: @client.name %>    
    <div class="new_form">
      <div>Name: <%= f.text_field :name %></div>
      <div>Photo: <%= f.file_field :image, accept:"image/*;capture=camera" %></div>
      <div>Sound : <%= f.file_field :audio, accept:"audio/*;capture=microphone" %></div>
      <div>Position : <%= f.select :position, [1,2,3,4,5,6,7,8,9] %></div>
    </div>
    <%= submit_tag 'Save' %>
  <% end %>
</section>

app/views/items/show.html.erb
<%= render "items/group_page_#{@mode}", items: @items ,current_item: @item%>

<script type="text/javascript">
  mixpanel.track('View item', {
    'id': '<%= params[:client_id] %>',
    'mode': '<%= @mode %>',
    'item name': '<%= @item.name %>'
  });
</script>

app/views/items/show_choice.html.erb
<section class="chosen-item-callout">

  <h1 class="chosen-item-callout__heading"><%= @item.name%></h1>
  <img id="item_image" class="chosen-item-callout__image" src="<%= image_item_path(@item, format: :jpg) %>"/>
  <audio id="item_audio" src="<%= audio_item_path(@item, format: :mpeg) %>" autoplay="true" autobuffer="true" ></audio>
  <span class="chosen-item-callout__done">
    <a href="<%=client_path(@item.client.name)%>" class="choice_done"><i class="fa fa-check"></i></a>
    <a href="<%=client_path(@item.client.name)%>" class="choice_cancelled"><i class="fa fa-times"></i></a>
  </span>
  <div id="delete_step2">
    <%= button_to 'Confirm Delete', client_item_path(@client.name, @item), method: :delete, class: 'chosen-item-callout__delete__link' %>
  </div>
</section>
<script>
var itemAudio = $("#item_audio")[0];
$("#item_image")
	.on("click",function() {
		itemAudio.play();
	});
</script>

<script type="text/javascript">
  mixpanel.track('Show choice', {
    'id': '<%= params[:client_id] %>',
    'mode': '<%= @mode %>',
    'item name': '<%= @item.name %>'
  });
</script>

app/views/layouts/_mixpanel.html.erb
<!-- start Mixpanel --><script type="text/javascript">(function(e,b){if(!b.__SV){var a,f,i,g;window.mixpanel=b;b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable time_event track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.set_once people.increment people.append people.union people.track_charge people.clear_charges people.delete_user".split(" ");
for(g=0;g<i.length;g++)f(c,i[g]);b._i.push([a,e,d])};b.__SV=1.2;a=e.createElement("script");a.type="text/javascript";a.async=!0;a.src="undefined"!==typeof MIXPANEL_CUSTOM_LIB_URL?MIXPANEL_CUSTOM_LIB_URL:"file:"===e.location.protocol&&"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js".match(/^\/\//)?"https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js":"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";f=e.getElementsByTagName("script")[0];f.parentNode.insertBefore(a,f)}})(document,window.mixpanel||[]);
mixpanel.init("af4c14751e3923ea7f5e23bfc685548e");</script><!-- end Mixpanel -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html manifest="/cache.manifest">
<head>
  <title>BenjamRails</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="initial-scale=1, maximum-scale=1">

  <%= render 'layouts/mixpanel' %>
</head>
<body>
    <!-- Fixed navbar -->
    <div>
      <nav class="navbar navbar-default" role="navigation">
        <div>
          <%= image_tag "user_ben.png",class: 'user' %>
        </div>
        <div class="navbar-header">
          <a href="<%=client_path(@client.name)%>">
            <%= image_tag "i_home.png",class: 'home' %>
          </a>
        </div>

        <%unless @item && @item.id%>
          <div>
            <a class="delayed-action" href="<%=new_client_item_path(@client.name)%>">
              <%= image_tag "i_add_grey.png",class: 'edit' %>
            </a>
          </div>
        <%end%>  

        <%if @item && @item.id%>
          <div>
            <a class="delayed-action" href="<%=client_item_nested_path(@client.name, @item)%>">
              <%= image_tag "i_add_grey.png",class: 'edit' %>
            </a>
          </div>

          <%if @item.children.none?%>

              <%= image_tag "i_minus_grey.png",class: 'delete',id: "delete_step1" %>         
             <div id="delete_step1">
            </div>
			
          <%end%>         

        <%end%>

        <div id="scroll-mode" style="margin: 10px;">
          <a href="<%=client_chooser_path(@client.name) %>">
            <span style="color:grey"> Choose<br/>scrolling<br/>mode </span>
          </a>
        </div>

      </nav>

      <div>

        <%= yield %>

      </div>

      <div class="cache-progress-bar">
        <p>Cache load progress</p>
        <div class="cache-progress-bar__container">
          <div class="cache-progress-bar__progress"></div>
        </div>
        <div class="cache-progress-bar__text"></div>
      </div>

    </div> <!-- /container -->
	

    <script type="text/javascript">

mixpanel.identify('<%= params[:client_id] %>');
    </script>

</body>
</html>